apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-neo4j
  labels:
    app: neo4j
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - port: 7687
  selector:
    app: neo4j
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-neo4j
  labels:
    app: neo4j
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-neo4j
  selector:
    matchLabels:
      app: neo4j
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: neo4j
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: neo4j
          image: {{ .Values.neo4jImage }}
          ports:
            - containerPort: 7687
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-neo4j-auth
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-neo4j-auth
                  key: password
            - name: NEO4J_AUTH
              value: "$(DATABASE_USER)/$(DATABASE_PASSWORD)"
            - name: NEO4J_PLUGINS
              value: '["graph-data-science"]'
          startupProbe:
            tcpSocket:
              port: 7687
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 7687
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage }}
