apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solver
  labels:
    app: solver
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: solver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: solver
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: solver
          image: {{ .Values.solverImage }}
          ports:
            - containerPort: 3001
          startupProbe:
            tcpSocket:
              port: 3001
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solver
  labels:
    app: solver
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 3001
  selector:
    app: solver
    release: {{ .Release.Name }}
