apiImage: ghcr.io/leonardjouve/trailr-api:latest
solverImage: ghcr.io/leonardjouve/trailr-solver:latest
neo4jImage: neo4j:2026.06.0
storage: 10Gi
host: trail.famillejouve.ch

tiles:
  url: https://github.com/LeonardJouve/trailr/releases/latest/download/trails-tiles.zip
  sha256: ""

neo4jBootstrap:
  enabled: false
  url: https://github.com/LeonardJouve/trailr/releases/latest/download/trails.zip
  sha256: ""
  maxOffHeapMemory: 1G
