syntax = "proto3";

package ch.trailr;

option java_package = "ch.trailr.solver";
option java_multiple_files = true;
option go_package = "github.com/LeonardJouve/trailr/api/src/proto";

service TrailSolver {
    rpc SolveTour(SolveTourRequest) returns (SolveTourResponse);
}

message SolveTourRequest {
    int32 origin_id = 1;
    double target_length = 2;
    double target_elevation = 3;
    repeated Node nodes = 4;
    repeated Edge edges = 5;
    double length_penalty_weight = 6;
    double elevation_penalty_weight = 7;
    double repeat_penalty_weight = 8;
    double exponential_length_penalty_weight = 9;
    double time_limit_seconds = 10;
}

message SolveTourResponse {
    bool found = 1;
    double length = 2;
    double elevation = 3;
    repeated int32 node_ids = 4;
    repeated string edge_ids = 5;
}

message Coordinate {
    double x = 1;
    double y = 2;
    double z = 3;
}

message Node {
    int32 id = 1;
    Coordinate coordinate = 2;
}

message Edge {
    string uuid = 1;
    TrailType trail_type = 2;
    SurfaceType surface_type = 3;
    int32 from_node = 4;
    int32 to_node = 5;
    double length = 6;
    repeated Coordinate coordinates = 7;
}

enum SurfaceType {
    UNSET = 0;
    ROAD = 100;
    PATH = 200;
    UNKNOWN = 999997;
    NONE = 999998;
}

enum TrailType {
    HIKING_TRAIL = 0;
    MOUNTAIN_HIKING_TRAIL = 1;
    ALPINE_HIKING_TRAIL = 2;
    OTHER = 3;
}